name: Terraform Deploy qa/staging/prod in us-east-1 and us-west-2

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
        type: choice
        options:
          - us-east-1
          - us-west-2
      environment:
        description: 'Environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - prod
          - qa
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Checkov
      run: pip install checkov

    - name: Run Checkov scan
      run: checkov -d ./infra

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init -backend-config="bucket=${{ secrets.TF_VAR_STATE_BUCKET }}" -backend-config="key=${{ github.event.inputs.region }}/${{ github.event.inputs.environment }}/terraform.tfstate"
      working-directory: ./infra

    - name: Validate Terraform
      run: terraform validate
      working-directory: ./infra

    - name: Plan Terraform
      run: terraform plan -var-file=environments/${{ github.event.inputs.region }}_${{ github.event.inputs.environment }}.tfvars -out=plan.tfplan
      working-directory: ./infra

    - name: Apply Terraform
      run: terraform apply plan.tfplan
      working-directory: ./infra
