name: Terraform Deploy qa/staging/prod in us-east-1 and us-west-1

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
        type: choice
        options:
          - us-east-1
          - us-west-1
      environment:
        description: 'Environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - prod
          - qa
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./regions/${{ github.event.inputs.region }}/${{ github.event.inputs.environment }}

    - name: Validate Terraform
      run: terraform validate
      working-directory: ./regions/${{ github.event.inputs.region }}/${{ github.event.inputs.environment }}

    - name: Plan Terraform
      run: terraform plan -var-file=${{ github.event.inputs.environment }}.tfvars -out=plan.tfplan
      working-directory: ./regions/${{ github.event.inputs.region }}/${{ github.event.inputs.environment }}

    - name: Apply Terraform
      if: github.event.inputs.environment == 'qa'
      run: terraform apply -var-file=${{ github.event.inputs.environment }}.tfvars -auto-approve plan.tfplan
      working-directory: ./regions/${{ github.event.inputs.region }}/${{ github.event.inputs.environment }}
